[package]
name = "igloo"
version = "0.1.0"
authors = ["Daniel"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shipyard = "0.4.1"
bracket-lib = "0.8.1"
